In [1]:
import pandas as pd

import config

from src.TimeEmulator import TimeEmulator

from data_loader import PROCESSED_DATA_DIR

In [2]:
df = pd.read_parquet(PROCESSED_DATA_DIR / 'online_retail.parquet')

In [3]:
MD_Emulate = TimeEmulator(
    start_date = '2011-09-08 00:00:00',
    df = df
)

In [5]:
forecast_df = MD_Emulate.emulate_time_change(n_ticks = 1, tick_size = config.tick_size)

C:\Users\UserB\Documents\ML\Online Retail II UCI\src\ModelClasses.py:35: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  X_today = X_transformed.groupby('StockCode').last().reset_index()

In [7]:
daily_grid = forecast_df.unstack(level='StockCode')
daily_grid = daily_grid.resample('D').bfill()
upsample_forecast = daily_grid.stack(level='StockCode')

C:\Users\UserB\AppData\Local\Temp\ipykernel_13524\3477645067.py:3: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  upsample_forecast = daily_grid.stack(level='StockCode')

In [8]:
forecast_df

                         predicted_quantity  optimal_price
forecast_date StockCode
2011-09-20    10002                    18.0       1.700000
              10125                     9.0       1.700000
              10133                    45.0       0.840000
              10135                    11.0       2.742000
              11001                    13.0       3.380000
...                                     ...            ...
              90200D                    2.0       8.300000
              C2                        1.0     100.000000
              DOT                      10.0     638.520000
              M                        14.0     625.832000
              POST                     92.0      42.555556

[2320 rows x 2 columns]

In [8]:
upsample_forecast

                         predicted_quantity  optimal_price
forecast_date StockCode
2011-09-13    10002                    18.0       1.700000
              10125                     9.0       1.700000
              10133                    45.0       0.840000
              10135                    12.0       2.500000
              11001                    17.0       3.380000
...                                     ...            ...
2011-10-25    90200C                    1.0       8.300000
              C2                        2.0     100.000000
              DOT                      10.0     757.358000
              M                        55.0      20.364280
              POST                     70.0      40.357241

[102157 rows x 2 columns]

In [ ]:
prediction.to_parquet(IPC_PATH / 'MD_prediction_buffer.parquet')